name: Upload to Roblox (Dev)

on:
  push:
    branches:
      - dev

jobs:
  upload:
    runs-on: ubuntu-latest
    environment: ROBLOX-SECURITY-TOKEN

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Cache unzip .deb
        id: unzip-cache
        uses: actions/cache@v3
        with:
          path: ./unzip.deb
          key: unzip-ubuntu-deb

      - name: Download unzip .deb
        if: steps.unzip-cache.outputs.cache-hit != 'true'
        run: |
          curl -o unzip.deb http://archive.ubuntu.com/ubuntu/pool/main/u/unzip/unzip_6.0-26ubuntu1_amd64.deb

      - name: Install unzip
        run: |
          sudo dpkg -i unzip.deb || sudo apt-get install -f -y

      - name: Cache Rojo
        id: rojo-cache
        uses: actions/cache@v3
        with:
          path: /usr/local/bin/rojo
          key: rojo-linux-x86_64-7.5.1

      - name: Download and install Rojo
        if: steps.rojo-cache.outputs.cache-hit != 'true'
        run: |
          curl -sL -o rojo.zip https://github.com/rojo-rbx/rojo/releases/latest/download/rojo-7.5.1-linux-x86_64.zip
          unzip -q rojo.zip
          chmod +x rojo
          sudo mv rojo /usr/local/bin/rojo

      - name: Rename Package
        run: |
          sed -i 's/"name": "Slate"/"name": "Slate-dev"/' default.project.json

      - name: Upload to Roblox
        env:
          ROBLOSECURITY: ${{ secrets.ROBLOX_SECURITY }}
        run: |
          rojo upload --asset_id 72441735686914 --cookie "$ROBLOSECURITY"

  notify:
    needs: upload
    runs-on: ubuntu-latest
    environment: DISCORD-WEBHOOK-URL
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Send webhook notification with latest commits
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: |
          COMMITS=$(git log -5 --pretty=format:'`%h` %s - %an' | jq -R . | jq -s .)
          DESCRIPTION=$(echo $COMMITS | jq -r 'join("\n")')

          PAYLOAD=$(jq -n --arg desc "$DESCRIPTION" '{
            "content": null,
            "embeds": [
              {
                "title": "Slate-dev Package Update",
                "description": $desc,
                "url": "https://github.com/NoahIsADeveloper/Slate",
                "color": 1274803
              }
            ],
            "attachments": []
          }')

          curl -X POST -H "Content-Type: application/json" -d "$PAYLOAD" "${{ secrets.WEBHOOK_URL }}"