name: Upload to Roblox (Dev)

on:
  push:
    branches:
      - dev

jobs:
  upload:
    runs-on: ubuntu-latest
    environment: ROBLOX-SECURITY-TOKEN

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install unzip
        run: sudo apt-get update && sudo apt-get install -y unzip

      - name: Cache Rojo
        id: rojo-cache
        uses: actions/cache@v3
        with:
          path: /usr/local/bin/rojo
          key: rojo-linux-x86_64-7.5.1

      - name: Download and install Rojo
        if: steps.rojo-cache.outputs.cache-hit != 'true'
        run: |
          curl -sL -o rojo.zip https://github.com/rojo-rbx/rojo/releases/latest/download/rojo-7.5.1-linux-x86_64.zip
          unzip -q rojo.zip
          chmod +x rojo
          sudo mv rojo /usr/local/bin/rojo

      - name: Rename Package
        run: |
          sed -i 's/"name": "Slate"/"name": "Slate-dev"/' default.project.json

      - name: Upload to Roblox
        env:
          ROBLOSECURITY: ${{ secrets.ROBLOX_SECURITY }}
        run: |
          rojo upload --asset_id 72441735686914 --cookie "$ROBLOSECURITY"